#!/bin/bash
set -euo pipefail

DRY_RUN=
while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run)
      DRY_RUN=1
      ;;
    -h|--help)
      usage
      ;;
    -*=)
      echo "Error: unknown flag $1" >&2
      exit 1
      ;;
    *)
      usage
      ;;
  esac
  shift
done

apt_pkgs=(
    # apt
    apt-transport-https
    ca-certificates
    apt-file
    software-properties-common # for add-apt-repository (unfortunate side-effect: software-properties-common pulls in packagekit)
    bash-completion

    # X11/i3
    xorg
    xserver-xorg-input-synaptics
    dbus-x11
    x11-utils # for xev, xwininfo, ...
    xdotool
    xbacklight # alternative - light
    xinput
    xbindkeys
    xvkbd
    arandr
    xclip
    autocutsel
    compton
    i3
    i3status
    i3lock
    rofi
    dunst
    feh
    libnotify-bin
    xautolock
    rxvt-unicode
    at # used by root/etc/udev/rules.d/*

    # gnome/GTK
    lxappearance
    arc-theme
    adwaita-icon-theme-full
    gnome-screenshot
    gnome-system-monitor
    gnome-disk-utility
    gnome-calculator
    dconf-editor
    cheese
    nautilus
    file-roller
    baobab
    evince
    eog
    solaar
    redshift
    safeeyes # https://www.dejal.com/timeout/ on macOS
    pavucontrol
    volumeicon-alsa
    playerctl
    font-manager
    font-viewer
    fonts-dejavu
    fonts-font-awesome
    fonts-liberation2
    fonts-noto
    hunspell hunspell-en-us
    meld
    flameshot # macOS - https://github.com/lupoDharkael/flameshot/issues/586
    cups
    system-config-printer

    vlc
    firefox
    dosbox

    # CLI tooling
    build-essential # for make
    procps # for watch
    git lighttpd
    atool unzip unrar bzip2 xz-utils
    progress # https://github.com/xfennec/progress
    ripgrep
    jq
    fasd
    direnv
    neovim
    ncdu
    expect
    bc
    curl
    htop
    elfutils # https://en.wikipedia.org/wiki/GNU_Binutils
    imagemagick

    msr-tools # for wrmsr/rdmsr
    util-linux # for lscpu - https://en.wikipedia.org/wiki/util-linux

    # network
    network-manager-gnome
    network-manager-openconnect-gnome
    blueman
    ntp
    iproute2 # for ip, ss, ...
    ldnsutils # for drill (drill if you can, dig if you have to, nslookup if you must)
    mtr-tiny
    socat
    tcpdump tcpflow ngrep mitmproxy wireshark-gtk

    # security
    policykit-1-gnome
    gpg gpg-agent pinentry-gtk2
    seahorse
    scdaemon pcscd # for gpg2 --card-status
    openssh-client # for ssh-copy-id
)

apt_install_opt=
if [[ "$DRY_RUN" == "1" ]]; then
    apt_install_opt=--dry-run
fi

set -x
sudo apt update -qq

# https://linux.die.net/man/8/apt-get
if (apt-get install --dry-run -yq "${apt_pkgs[@]}" 2>&1 || true) |
    grep -cqE '^Conf|^Inst|^Remv|^E:'; then
    sudo apt install $apt_install_opt -yq "${apt_pkgs[@]}"
fi
