#!/bin/bash
set -e

KUBESEC_VERSION=0.9.2

mkdir -p /tmp/pkgs/kubesec
cd /tmp/pkgs/kubesec

curl -sSL "https://github.com/shyiko/kubesec/releases/download/$KUBESEC_VERSION/kubesec-$KUBESEC_VERSION-$(
        bash -c '[[ $OSTYPE == darwin* ]] && echo darwin || echo linux'
    )-amd64" \
    -o kubesec
chmod +x kubesec
sudo mv -f kubesec /usr/local/bin/