#!/bin/bash
set -e

# https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-linux

# KUBECTL_VERSION="$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)"
KUBECTL_VERSION=v1.16.15

mkdir -p /tmp/pkgs/kubectl
cd /tmp/pkgs/kubectl

curl -sSL "https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/$(
        bash -c '[[ $OSTYPE == darwin* ]] && echo darwin || echo linux'
    )/amd64/kubectl" -o kubectl
chmod +x kubectl
sudo mv -f kubectl /usr/local/bin/kubectl
