#!/bin/bash
set -e

RESTIC_VERSION=0.9.6

mkdir -p /tmp/pkgs/restic
cd /tmp/pkgs/restic

curl -sSL "https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/restic_${RESTIC_VERSION}_$(
        bash -c '[[ $OSTYPE == darwin* ]] && echo darwin || echo linux'
    )_amd64.bz2" \
    -o restic-$RESTIC_VERSION.bz2
atool -q -x restic-$RESTIC_VERSION.bz2
chmod +x restic-$RESTIC_VERSION
sudo mv -f restic-$RESTIC_VERSION /usr/local/bin/restic
