#!/bin/bash
set -e

mkdir -p /tmp/pkgs/shfmt
cd /tmp/pkgs/shfmt

curl -sSL https://github.com/mvdan/sh/releases/download/v3.1.1/shfmt_v3.1.1_linux_amd64 \
    -o shfmt
chmod +x shfmt
sudo mv shfmt /usr/local/bin/
