#!/bin/bash
set -e

mkdir -p /tmp/pkgs/kustomize
cd /tmp/pkgs/kustomize

curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
sudo mv kustomize /usr/local/bin/

