#!/bin/bash
set -e

RESTIC_VERSION=0.16.2

mkdir -p /tmp/pkgs/restic
cd /tmp/pkgs/restic

curl -sSL "https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/restic_${RESTIC_VERSION}_linux_amd64.bz2" \
    -o restic-$RESTIC_VERSION.bz2
atool -q -x restic-$RESTIC_VERSION.bz2
chmod +x restic-$RESTIC_VERSION
sudo mv -f restic-$RESTIC_VERSION /usr/local/bin/restic
