#!/bin/bash
set -e

SHFMT_VERSION=3.7.0

mkdir -p /tmp/pkgs/shfmt
cd /tmp/pkgs/shfmt

curl -sSL https://github.com/mvdan/sh/releases/download/v${SHFMT_VERSION}/shfmt_v${SHFMT_VERSION}_linux_amd64 \
    -o shfmt
chmod +x shfmt
sudo mv shfmt /usr/local/bin/
