#!/bin/bash
set -e

TERRAFORM_VERSION=1.6.6

mkdir -p /tmp/pkgs/terraform
cd /tmp/pkgs/terraform

curl -sSL "https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" \
    -o terraform_$TERRAFORM_VERSION.zip
atool -q -x terraform_$TERRAFORM_VERSION.zip
sudo mv -f terraform /usr/local/bin/terraform
